export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReiews: 10,
    },
    {
      _id: "2",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 90,
      brand: "Nike",
      rating: 4.5,
      numReiews: 10,
    },
    {
      _id: "3",
      name: "Best Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 80,
      brand: "Nike",
      rating: 4.2,
      numReiews: 10,
    },
    {
      _id: "4",
      name: "Best Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 80,
      brand: "Nike",
      rating: 4.2,
      numReiews: 10,
    },
  ],
};
